name: .NET Backend CI

on:
  push:
    branches: [ main ] 
    paths:
      - 'API/**'
      - '.github/workflows/dotnet-ci.yml'
  pull_request:
    branches: [ main ] 
    paths:
      - 'API/**'
      - '.github/workflows/dotnet-ci.yml' 

jobs:
  build-dotnet:
    runs-on: ubuntu-latest 

    defaults:
      run:
        working-directory: ./API

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x.x' 

    - name: Restore dependencies
      run: dotnet restore ../sistema-gestion-inventario.sln

    - name: Build
      run: dotnet build ../sistema-gestion-inventario.sln --configuration Release --no-restore
